### ISSUE TITLE
duplicate target name causing collision in parent project

### ISSUE THREAD

**Issue by bolu-atx** [TheLartians/CPM.cmake#105]
Hi,

Let me preface this issue report with a huge congratulations. I love cpm.cmake, it solved a lot of dependency management I had with using cmake. and I am working on porting over my build system to use cpm.cmake exclusively.

I ran into an issue while using cpm.cmake with duplicate target names by trying to add two child cmake packages.

To reproduce:
```cmake
CPMAddPackage(
        NAME CLAPACK
        VERSION 3.2.1
        URL http://www.netlib.org/clapack/clapack-3.2.1-CMAKE.tgz
)

if(CLAPACK_ADDED)
  # Set include directories for the targets
  target_include_directories(f2c INTERFACE "${CLAPACK_SOURCE_DIR}/INCLUDE")
  target_include_directories(lapack INTERFACE "${CLAPACK_SOURCE_DIR}/INCLUDE")
endif()


CPMAddPackage(
        NAME Eigen
        VERSION 3.2.8
        URL https://gitlab.com/libeigen/eigen/-/archive/3.2.8/eigen-3.2.8.tar.gz
        OPTIONS
        "EIGEN_LEAVE_TEST_IN_ALL_TARGET 0"
)
```

The error I get when I run cmake:

```
CMake Error at cmake-build-debug/_deps/eigen-src/blas/CMakeLists.txt:15 (add_custom_target):
  add_custom_target cannot create target "blas" because another target with
  the same name already exists.  The existing target is a static library
  created in source directory
  "/Users/blu/Repos/kintek-explorer/cmake-build-debug/_deps/clapack-src/BLAS/SRC".
  See documentation for policy CMP0002 for more details.

CMake Error at cmake-build-debug/_deps/eigen-src/lapack/CMakeLists.txt:15 (add_custom_target):
  add_custom_target cannot create target "lapack" because another target with
  the same name already exists.  The existing target is a static library
  created in source directory
  "/Users/blu/Repos/kintek-explorer/cmake-build-debug/_deps/clapack-src/SRC".
  See documentation for policy CMP0002 for more details.
```

I can work around this issue by setting a CMake option to pick one or the other, but was wondering if there's a way to add "namespace" to target names to avoid this from the package manager itself?

**Comment by TheLartians** [comment]
Hey, happy to hear CPM.cmake is working well for you! 
About your issue, if I remember correctly Eigen is header only library and from the looks of it their CMakeLists.txt are not intended for anything but testing of the Eigen library itself. Instead, I'd recommend to create simply create your own Eigen target, that sets the correct include directory:

```cmake
CPMAddPackage(
  NAME Eigen
  VERSION 3.2.8
  URL https://gitlab.com/libeigen/eigen/-/archive/3.2.8/eigen-3.2.8.tar.gz
  # Eigen's CMakelists are not intended for library use
  DOWNLOAD_ONLY YES 
)

if(Eigen_ADDED)
  add_library(Eigen INTERFACE IMPORTED)
  target_include_directories(Eigen INTERFACE ${Eigen_SOURCE_DIR})
endif()

add_executable(test test.cpp)
target_link_libraries(test Eigen)
```

This allows me to compile and run the Eigen examples without issues.

> I can work around this issue by setting a CMake option to pick one or the other, but was wondering if there's a way to add "namespace" to target names to avoid this from the package manager itself?

This is an interesting idea, however it would require changing a lot of how the CMake machinery works. Also it's potentially unsafe as libraries with the same name have a high probability of exporting symbols with the same name which would lead to ODR violations and break your build without warning.

**Comment by bolu-atx** [comment]
That's fair, we'll probably get link time warnings even if we can configure the CMake target without issue.

Thanks for the reply @TheLartians, really appreciate it!

**Comment by TheLartians** [comment]
No problem, did the custom target solve the issue for you?

**Comment by bolu-atx** [comment]
@TheLartians  thank you for your help!

I've updated the wiki snippet page with the snippets that I used for my project.
https://github.com/TheLartians/CPM.cmake/wiki/More-Snippets

**Comment by bolu-atx** [comment]
Hi, I did not realize that Eigen was a header only library, your solution of importing it as an Interface library worked! Thanks
