### ISSUE TITLE
VERSION option adds "v" prefix resulting in invalid tags

### ISSUE THREAD

**Issue by lolleko** [TheLartians/CPM.cmake#106]
using:

```
CPMAddPackage(
  NAME glfw
  GITHUB_REPOSITORY glfw/glfw
  VERSION 3.3.2
  OPTIONS
    "CXXOPTS_BUILD_EXAMPLES Off"
    "CXXOPTS_BUILD_TESTS Off"
)
```

CPM adds a `v` to the version tag

which results in:

```
CMake Error at glfw-subbuild/glfw-populate-prefix/tmp/glfw-populate-gitclone.cmake:40 (message):
  Failed to checkout tag: 'v3.3.2'
```

Because glfw does not prefix it's version tags with v (https://github.com/glfw/glfw/tree/3.3.2).

**Comment by lolleko** [comment]
nvm just found `GIT_TAG` param.

But to be honest the `VERSION `parameter is a bit confusing, what's the benefit of having an extra `VERSION` option instead of just `GIT_TAG`

**Comment by TheLartians** [comment]
Hey, I'm glad you solved it! In general, the `GIT_TAG` is for the git tag and the version is for specifying the (lexical) version number of the package, so CPM.cmake is able to emit a warning when a dependency asks for a more recent version of a dependency than currently used. As different packages will ask for different versions of a dependency, the idea is to have them available in a minimum required version.
As the tag and the version are often closely related we decided it would be convenient to have CPM.cmake set `VERSION` to `<GIT_TAG>`, or `GIT_TAG` to `v<VERSION>` if one or the other is not explicitly specified.

**Comment by Leon0402** [comment]
As this has been marked a duplicate of similar issues, I will answer in here: 

I agree with your comments @TheLartians that prefixing with v is common (and recommend by GitHub). I do think that a version number without any v prefix is very common as well. 
So to make life a little bit easier why not support both? 

If this is something that could be implemented, maybe the issue should be reopened

**Comment by TheLartians** [comment]
@Leon0402 I agree, which is why the version is automatically inferred If only the `GIT_TAG` is provided in a suitable format. Also note the shorthand syntax, that supports an easy notation for providing only the tag.

```cmake
# A git package from a given uri with a version
CPMAddPackage("uri@version")
# A git package from a given uri with a git tag or commit hash
CPMAddPackage("uri#tag")
# A git package with both version and tag provided
CPMAddPackage("uri@version#tag")
```

For example, the `range-v3` can be fetched using simply `CPMAddPackage("gh:ericniebler/range-v3#0.11.0")`.

**Comment by iboB** [comment]
Technically we could make use of something in the lines of `git ls-remote` to query available tags and see whether they are in the form of "A.B.C" or "vA.B.C". However I think that something like this is too big and risky to do at this point. Perhaps it's a good idea for the (not-so-near) future

**Comment by IronAttorney** [comment]
Is `version` able to be something other than a tag then? There are 3rd party repos without tags I wish to use in my current project where I am using CPM manager for all 3rd party package management for the first time.
