### ISSUE TITLE
subcommand failing when using CPM_SOURCE_CACHE on Windows

### ISSUE THREAD

**Issue by ryanwinter** [TheLartians/CPM.cmake#107]
When I active the CPM_SOURCE_CACHE, I get a subcommand failed error. It appears to be originating from [this](https://github.com/TheLartians/CPM.cmake/blob/464ba554c23c6aa60443bd9c77005beff82ff810/cmake/CPM.cmake#L221) line.

**executing:**
cmake -B_build -GNinja -DCMAKE_TOOLCHAIN_FILE="../../cmake/arm-gcc-cortex-m4.cmake" -DCPM_SOURCE_CACHE="C:\Users\ryanw/.cpm"

**results in:**
[1/9] Performing download step for 'threadx-populate'
':' is not recognized as an internal or external command,
operable program or batch file.
FAILED: threadx-populate-prefix/src/threadx-populate-stamp/threadx-populate-download
cmd.exe /C "cd /D D:\projects\iot\getting-started\Renesas\AE-CLOUD2\_build\_deps\threadx-subbuild\threadx-populate-prefix\src && : && "C:\Program Files\CMake\bin\cmake.exe" -E touch D:/projects/iot/getting-started/Renesas/AE-CLOUD2/_bu
ild/_deps/threadx-subbuild/threadx-populate-prefix/src/threadx-populate-stamp/threadx-populate-download"
ninja: build stopped: subcommand failed.

**Comment by TheLartians** [comment]
Hey thanks for the bug report! It would be great to have the `CPM_SOURCE_CACHE` work on windows as well. On unix systems, the colon (`:`) operator means "do nothing", which is the only way I know of to deactivate the download step in CMake. I'll try to find a cross-platform solution.

**Comment by ryanwinter** [comment]
Sounds great! I replaced it with a semicolon and this worked for me.

**Comment by TheLartians** [comment]
Oh thats great to know! the semicolon is an easy fix as it seems to work with unix bash shells as well. Version 0.19 is released and now uses semicolons instead of colons!

**Comment by TheLartians** [comment]
I was a bit too hasty about this fix, as it turns out ";" resolves into nothing in CMake (";" is used as a list element separator) and the download step is actually not disabled anymore. This means that offline packages will not work anymore. I've removed the release and will look for another fix. Sorry.

**Comment by TheLartians** [comment]
So that was more difficult than expected. v0.20 should now work offline and on all systems. 🎉

**Comment by ryanwinter** [comment]
Thanks Lars! I'll test it out.
