### ISSUE TITLE
How to only include public headers?

### ISSUE THREAD

**Issue by bolu-atx** [TheLartians/CPM.cmake#108]
Module in question
https://github.com/martell/pthreads-win32.cmake/blob/master/CMakeLists.txt

This is a cmake adaptation on top of the original pthreads-win32 library. The original library has header/source file in a single directory.

The cmake adaptation makes proper install targets and move the header/complied libs into the proper location (see below)

```cmake
install(TARGETS ${PTHREADS_LIBRARY}
	RUNTIME DESTINATION ${PTHREADS_BINDIR} COMPONENT ${PTHREADS_BINCOMPONENT}
	LIBRARY DESTINATION ${PTHREADS_LIBDIR} COMPONENT ${PTHREADS_LIBCOMPONENT}
	ARCHIVE DESTINATION ${PTHREADS_LIBDIR} COMPONENT ${PTHREADS_LIBCOMPONENT}
	PUBLIC_HEADER DESTINATION ${PTHREADS_INCLUDEDIR} COMPONENT ${PTHREADS_INCLUDECOMPONENT})
```

When adding this library using CPMAddPackage(), I needed to do something like
target_include_libraries(TARGET INTERFACE <PATH_TO_SOURCE_DIR>)
This adds all `.h` files as include headers, not just the public header.

My understanding is that CPM does not trigger the "install" step, but just the "configure/build" steps when adding a package.

Is there anyway to only include the public header?

Thank you!

Here's how I am adding that library via CPM
```cmake
# ---- pthreads for MSVC-----------
if(MSVC)
  CPMAddPackage(
          NAME pthreads-win32
          SOURCE_DIR ${PROJECT_SOURCE_DIR}/../../external/pthreads-win32
  )
  print_target_properties(pthreadsVC2)
endif()
```

The `print_target_properties` is a debug function to dump all target properties, its output is:
```
Library name of pthreads-win32: pthreadsVC2.
pthreadsVC2 AUTOGEN_ORIGIN_DEPENDS = ON
pthreadsVC2 AUTOMOC_COMPILER_PREDEFINES = ON
pthreadsVC2 AUTOMOC_MACRO_NAMES = Q_OBJECT;Q_GADGET;Q_NAMESPACE
pthreadsVC2 AUTOMOC_PATH_PREFIX = ON
pthreadsVC2 BINARY_DIR = C:/Users/justb/Repos/kintek-explorer/cmake-build-debug/_deps/pthreads-win32-build
pthreadsVC2 BUILD_WITH_INSTALL_RPATH = FALSE
pthreadsVC2 DEBUG_POSTFIX = d
pthreadsVC2 IMPORTED = FALSE
pthreadsVC2 IMPORTED_GLOBAL = FALSE
pthreadsVC2 INCLUDE_DIRECTORIES = C:/Users/justb/Repos/kintek-explorer/external/pthreads-win32/pthreads-win32
pthreadsVC2 INSTALL_NAME_DIR = @executable_path/../lib
pthreadsVC2 INSTALL_RPATH = $ORIGIN/../lib
pthreadsVC2 INSTALL_RPATH_USE_LINK_PATH = TRUE
pthreadsVC2 NAME = pthreadsVC2
pthreadsVC2 POSITION_INDEPENDENT_CODE = True
pthreadsVC2 PUBLIC_HEADER = C:/Users/justb/Repos/kintek-explorer/external/pthreads-win32/pthreads-win32/pthread.h;C:/Users/justb/Repos/kintek-explorer/external/pthreads-win32/pthreads-win32/sched.h;C:/Users/justb/Repos/kintek-explorer/external/pthreads-win32/pthreads-win32/semaphore.h
pthreadsVC2 SKIP_BUILD_RPATH = FALSE
pthreadsVC2 SOURCES = C:/Users/justb/Repos/kintek-explorer/external/pthreads-win32/pthreads-win32/attr.c;C:/Users/justb/Repos/kintek-explorer/external/pthreads-win32/pthreads-win32/barrier.c;C:/Users/justb/Repos/kintek-explorer/external/pthreads-win32/pthreads-win32/cancel.c;C:/Users/justb/Repos/kintek-explorer/external/pthreads-win32/pthreads-win32/cleanup.c;C:/Users/justb/Repos/kintek-explorer/external/pthreads-win32/pthreads-win32/condvar.c;C:/Users/justb/Repos/kintek-explorer/external/pthreads-win32/pthreads-win32/create.c;C:/Users/justb/Repos/kintek-explorer/external/pthreads-win32/pthreads-win32/dll.c;C:/Users/justb/Repos/kintek-explorer/external/pthreads-win32/pthreads-win32/autostatic.c;C:/Users/justb/Repos/kintek-explorer/external/pthreads-win32/pthreads-win32/errno.c;C:/Users/justb/Repos/kintek-explorer/external/pthreads-win32/pthreads-win32/exit.c;C:/Users/justb/Repos/kintek-explorer/external/pthreads-win32/pthreads-win32/fork.c;C:/Users/justb/Repos/kintek-explorer/external/pthreads-win32/pthreads-win32/global.c;C:/Users/justb/Repos/kintek-explorer/external/pthreads-win32/pthreads-win32/misc.c;C:/Users/justb/Repos/kintek-explorer/external/pthreads-win32/pthreads-win32/mutex.c;C:/Users/justb/Repos/kintek-explorer/external/pthreads-win32/pthreads-win32/nonportable.c;C:/Users/justb/Repos/kintek-explorer/external/pthreads-win32/pthreads-win32/private.c;C:/Users/justb/Repos/kintek-explorer/external/pthreads-win32/pthreads-win32/rwlock.c;C:/Users/justb/Repos/kintek-explorer/external/pthreads-win32/pthreads-win32/sched.c;C:/Users/justb/Repos/kintek-explorer/external/pthreads-win32/pthreads-win32/semaphore.c;C:/Users/justb/Repos/kintek-explorer/external/pthreads-win32/pthreads-win32/signal.c;C:/Users/justb/Repos/kintek-explorer/external/pthreads-win32/pthreads-win32/spin.c;C:/Users/justb/Repos/kintek-explorer/external/pthreads-win32/pthreads-win32/sync.c;C:/Users/justb/Repos/kintek-explorer/external/pthreads-win32/pthreads-win32/tsd.c;C:/Users/justb/Repos/kintek-explorer/external/pthreads-win32/pthreads-win32/pthread.h;C:/Users/justb/Repos/kintek-explorer/external/pthreads-win32/pthreads-win32/sched.h;C:/Users/justb/Repos/kintek-explorer/external/pthreads-win32/pthreads-win32/semaphore.h;C:/Users/justb/Repos/kintek-explorer/external/pthreads-win32/pthreads-win32/version.rc
pthreadsVC2 SOURCE_DIR = C:/Users/justb/Repos/kintek-explorer/external/pthreads-win32
pthreadsVC2 TYPE = SHARED_LIBRARY
pthreadsVC2 UNITY_BUILD_BATCH_SIZE = 8 
```

**Comment by TheLartians** [comment]
Hey I can take a look later, but in general `CPM.cmake` does the same as if you would include the target via `add_subdirectory`, so all targets and install commands from the main `CMakeLists.txt` will be added to the project. If the targets are written with [modern CMake practices](https://pabloariasal.github.io/2018/02/19/its-time-to-do-cmake-right/) there should be no need to modify the targets using `target_include_libraries`.
If you only want to include a specific directory and ignore everything else in the projects CMakeLists, you can add the `DOWNLOAD_ONLY` flag to `CPMAddProject` and define a custom target between `if (pthreads-win32_ADDED) ... endif()`.
The [wiki](https://github.com/TheLartians/CPM.cmake/wiki/More-Snippets) should have some snippets to help you get started.

**Comment by bolu-atx** [comment]
@TheLartians  Thank you, this is not a blocker, just something that bugs me in terms of code organization.

For larger projects, what if there's a header name collision? And if it's an external library, i don't really want to modify the external source to re-structure their include into interface / private includes.

**Comment by TheLartians** [comment]
> For larger projects, what if there's a header name collision? 

Then the first header found according to the [compiler's search rules](https://gcc.gnu.org/onlinedocs/cpp/Search-Path.html) will be used.

**Comment by bolu-atx** [comment]
@TheLartians do you have any suggestions on how to trigger "build" at configure time or whether that will be a feature might be for a future version of CPM?

**Scenario in question**
Library A (i.e. curl) depends on Library B (openssl) via (find_package()), I import library A and library B both via CPM, library's B target exists, but library A's CMakeLists fails since find_package() fails.

How I'm getting around it at the moment. I do not import Library B via CPM, but pre-install it via brew for mac / vcpkg for linux/windows, and basically exit with warning for the moment. It would be much nicer to not do this and have everything built during CMake build step. But I don't see how that's possible without changing CMakeLists rules of library A. (Maybe something like vcpkg apply patch before running cmake configure on the dependent project may be possible?)

**Comment by TheLartians** [comment]
Hm that's a good question, I do see the advantage of being able to override project dependencies that are using the regular `find_package` command. I think it should be possible to have CPM automatically generate `FindXXX.cmake` modules in a custom `CMAKE_MODULE_PATH` each time a CPM package is added in the project. That way it could also be used to override locally installed libraries etc when needed.

**Comment by bolu-atx** [comment]
@TheLartians That sounds like a great option.. I was able to finally get around dependending on brew/vcpkg external package managers with this dependency by doing a configure time build using ExternalProject, but it's not pretty.

**Comment by TheLartians** [comment]
@bolu-atx I've added the capability in #112. Could you test with the new [`CPM.cmake`](https://github.com/TheLartians/CPM.cmake/blob/1d5bcc1eb90d2d5492264cc8f8a57b09dee447fe/cmake/CPM.cmake) file and see if it resolves your issue?

**Comment by bolu-atx** [comment]
@TheLartians 
I pulled your latest changeset and tried it:

Are you referring to these generated .CMAKE modules?

![image](https://user-images.githubusercontent.com/20103637/80412427-b3aff280-8882-11ea-8fce-f9a29ec3f4ee.png)

I was wondering if it's possible to provide an optional argument when doing CPMAddPackage to not assume the find_package() name is the same as the package name. A lot of cmakelists wrappers for older libraries do not have the same name as the target.

For example, openssl-cmake (https://github.com/janbar/openssl-cmake) does not have openssl as the project name, so find_package(OpenSSL) still fails.

**Comment by TheLartians** [comment]
Well using the project name as the package name is simply a recommendation to stay consistent. In this case it would definitely be justifiable to simply use `OpenSSL` as the CPM package name.
Only thing to consider is that the targets in the `OpenSSL` CMake should be the same as with `find_package`, but that should also be possible to fix using alias libraries for example.

**Comment by bolu-atx** [comment]
@TheLartians I would tend to agree if I maintained that package. openssl-cmake is actualy a Cmakelist wrapper that someone on Github contributed, I could fork it and rename it to my intent tho.. so maybe this is not a use-case that CPM should worry about.

**Comment by TheLartians** [comment]
Hm maybe I'm misunderstanding the problem, but I wouldn't touch the source repository. What I meant was to add `OpenSSL-cmake` library simply using the name `OpenSSL` (as that would be the correct libraries name).

```cmake
CPMAddPackage(
  NAME OpenSSL
  GITHUB_REPOSITORY janbar/openssl-cmake
  GIT_TAG 1.1.1e-20200319
)

# now you can use find_package(OpenSSL) without creating duplicate targets
find_package(OpenSSL REQUIRED)
```

**Comment by bolu-atx** [comment]
Ah I see, I will try that. Thank you @TheLartians

**Comment by bolu-atx** [comment]
Maybe I'm going crazy, but I could not get curl and openssl to play nice with each other in cmake. I am almost ready to give up and just go with pre-compiled curl libraries for each platform I'll be deploying on. I think this is not because of CPM, but because of the poor Cmakelists build system in cURL. So Feel free to disregard my request for help :) It is definitely not CPM's fault.

I have this toy program setup to replicate the issue. This should fail on Windows 10 (I can't use https protocol, the test program fails, but libcurl compiles) and MacOS (I get an error about linking with a wrong version of libcrypto /usr/lib/libcrypto.dylib - which I believe is because cURL is not using the OpenSSL package I added via CPM). I tested it on Linux and that doesn't fail (because i have OpenSSL development package installed, cURL automatically finds that)

## CMakeLists.txt
```cmake
CMAKE_MINIMUM_REQUIRED(VERSION 3.15)
PROJECT(test-curl
   LANGUAGES CXX)

#========== Add CPM package manager =================
set(CPM_DOWNLOAD_LOCATION "${CMAKE_BINARY_DIR}/cmake/CPM.cmake")
set(CPM_VERSION 0.18)

if(NOT EXISTS ${CPM_DOWNLOAD_LOCATION})
   message(STATUS "Downloading CPM.cmake")
   file(DOWNLOAD
https://github.com/TheLartians/CPM.cmake/releases/download/v${CPM_VERSION}/CPM.cmake
${CPM_DOWNLOAD_LOCATION})
endif(NOT EXISTS ${CPM_DOWNLOAD_LOCATION})
include(${CPM_DOWNLOAD_LOCATION})


#========== Add dependency =================
CPMAddPackage(
        NAME openssl-cmake
        GITHUB_REPOSITORY janbar/openssl-cmake
        GIT_TAG master
        OPTIONS
        "WITH_APPS OFF"
)
if (openssl-cmake_ADDED)
    set(OPENSSL_INCLUDE_DIR "${openssl-cmake_BINARY_DIR}/include")
    target_include_directories(ssl INTERFACE ${OPENSSL_INCLUDE_DIR})
    target_include_directories(crypto INTERFACE ${OPENSSL_INCLUDE_DIR})
endif()

CPMAddPackage(
        NAME curl
        VERSION 7.67.0
        URL https://github.com/curl/curl/releases/download/curl-7_67_0/curl-7.67.0.tar.gz
        OPTIONS
        "CMAKE_USE_LIBSSH2 OFF"
        "BUILD_CURL_EXE OFF"
        "BUILD_SHARED_LIBS OFF"
        "HTTP_ONLY ON"
        "BUILD_TESTING OFF"
)

add_executable(test-curl main.cpp)
target_link_libraries(test-curl libcurl)
```


## main.cpp
```cpp
#include <iostream>
#include <string>
#include "curl/curlver.h"
#include "curl/curl.h"


static size_t WriteCallback(void *contents, size_t size, size_t nmemb,
void *userp)
{
    ((std::string*)userp)->append((char*)contents, size * nmemb);
    return size * nmemb;
}


int main() {
    std::cout << "hello world" << std::endl;
    std::cout << "LIBCURL VERSION: " << LIBCURL_VERSION << std::endl;
    CURL* curl;
    CURLcode res;
    std::string readBuffer;

    /* In windows, this will init the winsock stuff */
    curl_global_init(CURL_GLOBAL_ALL);

    curl = curl_easy_init();
    if (curl) {
        std::cout << "Testing cURL with https protocol\n";
        curl_easy_setopt(curl, CURLOPT_URL, "https://example.com");
        curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 1L);
        curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 1L);
        curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1L);
        curl_easy_setopt(curl, CURLOPT_POSTFIELDS, "testing=1");
        curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, WriteCallback);
        curl_easy_setopt(curl, CURLOPT_WRITEDATA, &readBuffer);

        /* Perform the request, res will get the return code */
        res = curl_easy_perform(curl);
        /* Check for errors */
        if (res != CURLE_OK) {
            fprintf(stderr, "curl_easy_perform() failed: %s\n",
                    curl_easy_strerror(res));
        }

        /* always cleanup */
        curl_easy_cleanup(curl);
    }
    curl_global_cleanup();
    std::cout << "Contents of CURL: " << readBuffer << std::endl;

    return 0;
}
```

**Comment by bolu-atx** [comment]
P.S. I also tried replacing the name of openssl-cmake package to OpenSSL to no avail. But the test program I posted did not have that change.

**Comment by TheLartians** [comment]
Yeah to be honest, I would avoid building dinosaur libraries like OpenSSL or Curl through CMake, but would rather use the Makefiles / tested third party scripts to create precompiled binaries for all supported platforms. It's really hard to say what's going on in those CMake scripts.
When we still had OpenSSL as a dependency we simply created a custom repo with a CMake script that would create an interface target to link to a precompiled library. Nowadays we luckily found more modern alternative libraries for our use-cases.

**Comment by bolu-atx** [comment]
Good to hear. Thanks!

**Comment by TheLartians** [comment]
Closing as the `find_package` functionality has been added in #112.
