### ISSUE TITLE
Use macros instead of functions

### ISSUE THREAD

**Issue by johelegp** [TheLartians/CPM.cmake#117]
I want to affect the scope from which `CPMFindPackage` is called to append the package's source directory to `CMAKE_MODULE_PATH`, as they contain my project's CMake modules. With `FetchContent` it is possible, as `FetchContent_MakeAvailable` (apparently a macro) eventually calls `add_subdirectory`.

The CMake modules repository `CMakeLists.txt` is
```CMake
list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}")
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} PARENT_SCOPE)
```

Before realizing this was possible, I just included its first line after the `FetchContent_MakeAvailable` call.

**Comment by TheLartians** [comment]
Good point, I see how that would be an expected outcome. However, I'm reluctant to change `CPMFindPackage` to a macro, as the current version defines a bunch of variables that I don't want leaking to the outer scope. Another issue is that the dependency can be added at any other point in the project (by a dependency or a dependant), in which case `CPMFindPackage` would not actually call `add_subdirectory`. This means that you would still never be sure if the current scope actually modified. Possible ways to resolve the issue for now are:

- If you have access to the dependency's `CMakeLists.txt`, you could define a function `updateModulePath()` that can be called from the outer package.
- Use the `DOWNLOAD_ONLY YES` flag and call `add_subdirectory(<dependency>_SOURCE_DIR)` manually after CPM.cmake has added the package.

**Comment by johelegp** [comment]
Ah, you're right about its shortcomings. Guess there's no way around having one extra line without making assumptions. Thank you.

I think this can be closed, but I'm hesitant to do it as you labelled it "enhancement".

**Comment by TheLartians** [comment]
Ah yes it can be closed, I was wondering if it still makes sense to use macros instead of functions for leading to the `add_subdirectory` call, but for now I guess it's not worth the effort.
