### ISSUE TITLE
[Feature Request] Use shallow clone for git repositories

### ISSUE THREAD

**Issue by kingsamchen** [TheLartians/CPM.cmake#129]
CPM currently clones full history for git-repository dependencies, which takes more time than necessary (in most cases) on downloading, and consumes more disk space.

Maybe use git shallow clone _by default_ for those dependencies?

There is a `GIT_SHALLOW` option to enable `--depth=1` with clone, which does what we exactly desire.

If I may, I would like to make a PR on it, :-)

**Comment by TheLartians** [comment]
Hey thanks for the suggestion and PR! I agree that it would be great to have `GIT_SHALLOW` enabled by default! However, as you can see from the CI failure, enabling `GIT_SHALLOW` can lead to unexpected failures as CMake fails to checkout certain branches or commits for some reason.

Until that is resolved, it's therefore currently safer to enable `GIT_SHALLOW` on a per-dependency basis, knowing when CMake will be able to successfully check out the commit. You can activate it by providing the `GIT_SHALLOW ON` argument together with the dependency source parameters in `CPMAddPackage`.

**Comment by kingsamchen** [comment]
According to this answer https://stackoverflow.com/questions/31278902/how-to-shallow-clone-a-specific-commit-with-depth-1 clone with `depth 1` won't work on a specific commit HASH. That is why the yaml example failed.

Maybe making `GIT_SHALLOW` a per-dependency option is a more practical approach.

**Comment by TheLartians** [comment]
> According to this answer https://stackoverflow.com/questions/31278902/how-to-shallow-clone-a-specific-commit-with-depth-1 clone with depth 1 won't work on a specific commit HASH. That is why the yaml example failed.

Shallow fetching a real git tag seems to work though, perhaps we can set a `SHALLOW` default behaviour when we detect the `GIT_TAG` to be an actual tag as opposed to a hash.

**Comment by kingsamchen** [comment]
A wonderful idea.

And maybe it is easier to identify out a hash from tag/branch value, because commit hash has fixed length and contains no characters other than hex digits.

While tags from different projects could use varied formats.

E.g for [standalone ASIO](https://github.com/chriskohlhoff/asio/releases), its release tag is in the form of `asio-1-23-4`; it doesn't even have prefix `v`, and yet uses `-` instead of conventional `.` as the version delimiter.

**Comment by kingsamchen** [comment]
@TheLartians Hi, I just made another commit on enabling shallow clone conditionally. Could you please review the commits when you are free?

Any suggestion is welcome

**Comment by TheLartians** [comment]
Feature added in #130.
