### ISSUE TITLE
Using `CPM_SOURCE_CACHE` and `CPMFindPackage`, CPM still continues to download and configure the project each time

### ISSUE THREAD

**Issue by jeremyong** [TheLartians/CPM.cmake#136]
The caching aspect was the main reason I tried to give it a try but it doesn't seem to be working. Based on the title, is there something I'm missing about how this is supposed to work?

**Comment by TheLartians** [comment]
Well for one, the `CPM_SOURCE_CACHE` can only avoid the download step. The dependencies still need to be configured and built, as every project can have different configuration options. If you want to cache the build as well, check out projects such as [ccache](https://ccache.dev).

To test if the source cache works, you can try the following:

- In an empty directory create a file `CMakeLists.txt` containing the following:

```cmake
cmake_minimum_required(VERSION 3.14 FATAL_ERROR)

# ---- Project ----

project(Playground LANGUAGES CXX)

# ---- Fetch CPM ----

set(CPM_DOWNLOAD_LOCATION "${CMAKE_BINARY_DIR}/cmake/CPM.cmake")
set(CPM_DOWNLOAD_VERSION 0.27.1)

if(NOT (EXISTS ${CPM_DOWNLOAD_LOCATION} AND CPM_VERSION STREQUAL CPM_DOWNLOAD_VERSION))
  message(STATUS "Downloading CPM.cmake")
  file(DOWNLOAD https://github.com/TheLartians/CPM.cmake/releases/download/v${CPM_DOWNLOAD_VERSION}/CPM.cmake ${CPM_DOWNLOAD_LOCATION})
endif()

include(${CPM_DOWNLOAD_LOCATION})

# ---- Add dependencies via CPM ----

CPMFIndPackage(
  NAME BitLens
  GITHUB_REPOSITORY TheLartians/BitLens
  VERSION 2.2
)
```

- In a bash or similar shell run the following command from the directory:

```
CPM_SOURCE_CACHE=$(pwd)/deps cmake -H. -Bbuild
```

If everything worked there should now be two new directories in the current folder: `build`, containing the build, and `deps`, containing the dependency sources. You can verify that the cache works by creating a new build e.g. through: 

```
CPM_SOURCE_CACHE=$(pwd)/deps cmake -H. -Bbuild2
```

CPM.cmake should find the cached dependencies of the first build and no new download (besides the CPM.cmake source) will occur.

**Comment by TheLartians** [comment]
@jeremyong did this help you find the issue? 
If not, some details about what your tried so far and the output would be great. :)

**Comment by jeremyong** [comment]
Sorry for the lack of a response, for some reason I was under the impression that ccache support was built-in.

Regarding the "redownloading" of the files, I traced this to an actual VSCode bug on my machine that was not actually setting the cache directory properly. Sorry for troubling you (closing).

**Comment by TheLartians** [comment]
FYI if you're looking for an easy Ccache integration for Cmake, you might want to look at [ccache.cmake](https://github.com/TheLartians/Ccache.cmake).
