### ISSUE TITLE
How to use Howard Hinnant's date library with CPM?

### ISSUE THREAD

**Issue by fgr** [TheLartians/CPM.cmake#148]
I'm trying to use [Howard Hinnant's date library](https://github.com/HowardHinnant/date) with CPM.

This works:
```
CPMAddPackage(
        NAME HowardHinnant_date
        GITHUB_REPOSITORY HowardHinnant/date
        VERSION 3.0.0
)
```

But I have to use `#include "include/date/date.h"` to include the header. I want to get rid of the `include` part in the `#include` path (`#include "date/date.h"`).

I tried

```
if(HowardHinnant_date_ADDED)
    target_include_directories( HowardHinnant_date INTERFACE
            ${HowardHinnant_date_SOURCE_DIR}/include )
endif()
```

But cmake complains that target `HowardHinnant_date` is not build in my cmake project. So I changed this into (using the actual target's name (e.g., `myproject`))

```
if(HowardHinnant_date_ADDED)
    target_include_directories( myproject INTERFACE
            ${HowardHinnant_date_SOURCE_DIR}/include )
endif()
```

But still the pre-processor cannot find `date/date.h` in `#include "date/date.h"`.

**Comment by fgr** [comment]
Found a solution. Using `target_include_directories` was wrong. All I had to do was:

```
CPMAddPackage(
        NAME HowardHinnant_date
        GITHUB_REPOSITORY HowardHinnant/date
        VERSION 3.0.0
)

...

add_executable(mytarget_executable ...)

target_link_libraries(mytarget_executable date::date)
```

What I do not understand, though, is why I have to use `date::date` instead of something like `HowardHinnant_date::HowardHinnant_date` because the `NAME` property in `CPMAddPackage()` is `HowardHinnant_date` and not `date`.

**Comment by Andres6936** [comment]
It depends a lot on the documentation, in this case, the documentation of library you want to use is little.
But you should always try to check CMakeLists.txt and see which libraries are defined, for this case, look:

https://github.com/HowardHinnant/date/blob/313189b0a8767f9964704cfc87fe5956e12abc24/CMakeLists.txt#L62-L63

The library is being defined with the name `date` and an alias that is named `date::date`, so you should use `date::date` and not `HowardHinnant_date::HowardHinnant_date`.

**Comment by fgr** [comment]
Thanks for the clarification @Andres6936 I obviously have to learn more about CMake.

**Comment by fgr** [comment]
Added information on how to use the date library with CPM [to the wiki](https://github.com/TheLartians/CPM.cmake/wiki/More-Snippets#howard-hinnants-date-library).
