### ISSUE TITLE
Include 3rd parties as SYSTEM

### ISSUE THREAD

**Issue by friendlyanon** [TheLartians/CPM.cmake#151]
As mentioned in https://github.com/TheLartians/ModernCppStarter/issues/61#issuecomment-689843663 I would like to know if it's right for the libraries to not be made available as SYSTEM libraries?

Including as SYSTEM would mean that warnings set for the project using CPM would not falsely warn for code in 3rd party headers.

**Comment by TheLartians** [comment]
I agree that it would be a great to include directories from external dependencies as `SYSTEM` to avoid warnings. However afaik, I don't think CPM.cmake can do anything here, as the system keyword need too be used in the library's `CMakeLists.txt` when calling [target_include_directories](https://cmake.org/cmake/help/latest/command/target_include_directories.html).

This unfortunately leaves only the option of either ignoring the warnings around the bad `#include`s:

```cpp
// save compiler switches
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wpedantic"

// bad headers with problem goes here
#include <library/with/warnings>

// restore compiler switches
#pragma GCC diagnostic pop
```

Or, of course, you could ask the library maintainer to fix the warnings or you create a fix them in a PR yourself.

**Comment by friendlyanon** [comment]
I see, so this issue is outside the scope of CPM.cmake and can only be fixed on the dependency's side.
