### ISSUE TITLE
Help passing HTTP_PASSWORD value as a variable

### ISSUE THREAD

**Issue by vkaramov** [TheLartians/CPM.cmake#157]
I need to pass HTTP_USERNAME and HTTP_PASSWORD parameters as variables like this:
```
CPMAddPackage(
	NAME headers
	URL https://<my URL here>file.zip
	HTTP_PASSWORD ${NEXUS_PASSWORD}
	HTTP_USERNAME ${NEXUS_USER}
)
```

It works fine when I hardcode username and password but doesn't work when I use variables. Please help.

**Comment by TheLartians** [comment]
Do you mean it works if you set the username and password explicitly, e.g. `HTTP_USERNAME xxx`, but not if you set it as a variable? Have you checked if the variables are correctly defined? E.g. you could run 

```cmake
message("Username: ${NEXUS_USER}")`
message("Password: ${NEXUS_PASSWORD}")`
```

right before the CPM command and check the output.

**Comment by vkaramov** [comment]
Yes, I've printed these variables as you suggested, but still, see the issue.

**Comment by TheLartians** [comment]
Hm, if the variables have the exact same values that would work when hard-coded there should not be any difference as far as `CPMAddPackage` is concerned. Not really sure what could be the issue here.
