### ISSUE TITLE
SSH private gitlab

### ISSUE THREAD

**Issue by huand** [TheLartians/CPM.cmake#158]
suppose I have a private gitlab repo that I can clone with this command (SSH):

git clone git@gitlab.com:my-team/my-project.git

how do i do it with cpm?

it seems that cpm.cmake GITLAB_REPOSITORY want a https clone command

**Comment by TheLartians** [comment]
`GITLAB_REPOSITORY a/b` is a shortcut for `GIT_REPOSITORY https://gitlab.com/a/b.git`. For ssh, you should be able to just use the explicit command `GIT_REPOSITORY`:

```cmake
GIT_REPOSITORY git@gitlab.com:my-team/my-project.git
```

**Comment by TheLartians** [comment]
`GITLAB_REPOSITORY a/b` is a shortcut for `GIT_REPOSITORY https://gitlab.com/a/b.git`. For ssh, you should be able to just use the explicit command `GIT_REPOSITORY`:

```cmake
GIT_REPOSITORY git@gitlab.com:my-team/my-project.git
```

**Comment by huand** [comment]
thank you for quick reply, working fine!
