### ISSUE TITLE
Not compiling SDL2 when set to use a static library

### ISSUE THREAD

**Issue by DannyParker0001** [TheLartians/CPM.cmake#161]
```cmake
CPMAddPackage(
  NAME SDL2
  VERSION 2.0.12
  URL https://libsdl.org/release/SDL2-2.0.12.zip
  OPTIONS
    "SDL_SHARED Off"
)

add_executable (test "main.cpp" )
set_target_properties(test PROPERTIES CXX_STANDARD 20)
target_link_libraries(test SDL2)
```
I get an `Error	LNK1104	cannot open file 'SDL2.lib'`, SDL2.lib does not exist, it was not compiled.
Building with the shared library compiles fine.

**Comment by TheLartians** [comment]
Not really sure I can help you as this seems to be an issue with the SDL2 CMakeLists.
Maybe you could ask at the [SDL2 discourse](https://discourse.libsdl.org)?
