### ISSUE TITLE
Some projects don't prepend the tag with 'v' for the version

### ISSUE THREAD

**Issue by mtvee** [TheLartians/CPM.cmake#167]
Some projects don't use the 'v' when tagging. CPM.cmake assumes/adds a 'v' in front on the tag for VERSION. Perhaps it should just use what it is given? 

```
<+>UTF-8
===================================================================
--- cmake/CPM.cmake	(revision 42a2615a11b234c89fbbfb687bfabcfff35848d7)
+++ cmake/CPM.cmake	(date 1606469749260)
@@ -226,7 +226,7 @@
     if (DEFINED CPM_ARGS_GIT_REPOSITORY)
         list(APPEND CPM_ARGS_UNPARSED_ARGUMENTS GIT_REPOSITORY ${CPM_ARGS_GIT_REPOSITORY})
         if (NOT DEFINED CPM_ARGS_GIT_TAG)
-            set(CPM_ARGS_GIT_TAG v${CPM_ARGS_VERSION})
+            set(CPM_ARGS_GIT_TAG ${CPM_ARGS_VERSION})
         endif()
     endif()
```

**Comment by TheLartians** [comment]
From my experience, most projects actually do use the `v` prefix. Also the suggested format by GitHub, so imo it's reasonable to have it as the default. For all other conventions you can still explicitly specify `GIT_TAG` besides the version.

**Comment by TheLartians** [comment]
Also duplicate of #106 and #140.
