### ISSUE TITLE
Internal github repository?

### ISSUE THREAD

**Issue by hdf89shfdfs** [TheLartians/CPM.cmake#168]
Has CPM been tested with internal GitHub repositories?

My company will be switching to GitHub soon and obviously the repos aren't public.

So I'm curious how CPM works with internal repositories.

How does one go about signing/securing things? IE security problems.

If this is already possible and I didn't realize perhaps an explicit entry in the Wiki would be greatly beneficial.

**Comment by TheLartians** [comment]
Hey there! I'm using CPM.cmake for a number of private repositories. In fact most components of my project [Maphi](https://maphi.app) are closed source and managed with CPM.cmake. Internally CMake should just use standard `git` to clone a repository (via `ssh` or `https`), so anything you can already clone using `git` should work.

**Comment by hdf89shfdfs** [comment]
That makes sense. I believe the problem was primarily due to issues with our CI system when we experimented using regular fetch content. I'll get more details on work on Monday to add clarification to this issue.

**Comment by hdf89shfdfs** [comment]
Apologies I'll make sure to close this ticket. It was a bad implementation involved in the CI system.
