### ISSUE TITLE
[Feature] extract version from target

### ISSUE THREAD

**Issue by alexandreSalconiDenis** [TheLartians/CPM.cmake#169]
Dont know if I need to create an issue link with the pr #164 .

The issue is when you work with cmake and never install package on host, i.e when developing for embeded device.
This is a fix extract the version from the target itself if possible, 
I use that since we work with multiple lib for embedded prog.
In each lib we just had to set the Properties Version

I just put that at the end of all package I made:
```
get_target_property(_TARGET_TYPE ${PROJECT_NAME} TYPE)
if(_TARGET_TYPE STREQUAL "INTERFACE_LIBRARY")
    set_target_properties(${PROJECT_NAME} PROPERTIES INTERFACE_VERSION ${PROJECT_VERSION} )
else()
    set_target_properties(${PROJECT_NAME} PROPERTIES VERSION ${PROJECT_VERSION} )
endif()
```
with that the PROJECT_VERSION is the version selected by CPM.

**Comment by TheLartians** [comment]
Hm I'm not sure I'm a fan of the change as CPM.cmake relies on knowing the version before downloading the package. The reason is that we want to be able to warn about outdated versions if there is already an older version present. Why not directly pass the version tag to `CPMAddPackage`?

**Comment by alexandreSalconiDenis** [comment]
I understand, for us it was useful in case you close `dev` or `master` the version is then take from the package. And since it override only when defined if you dont use the pattern I mention it should not change your case. If I add a option in CPM, like `CPMPostVersionSelection` to enable this behavior could it be better?

**Comment by TheLartians** [comment]
Hm as I strongly discourage using branches as tag names (this may lead to unexpected offline and caching behaviour), I'm not sure such a feature makes sense in the core repo. How about defining and using an external function in your project / another package that you can call for this functionality?

Note that for simultaneous development on the dependency and dependent I recommend using a [local package override](https://github.com/TheLartians/CPM.cmake#local-package-override) instead. That would allow you to test new features in dependencies without needing to change the main CMakeLists until the new dependency's version is released.

**Comment by alexandreSalconiDenis** [comment]
we dont use branch as tag I may have mislead you in my example. The usage of branch as `GIT_TAG` is only during specific developement. The usage of extracting the version like I said is to be able to get a version from pacackage directly and not releate to a git tag or after an installation, also this solution work good with package that are `INTERFACES`. I wasnt able to create a module to wrap around CPM since it need to validate the version at the same stage it's currently done inside CPM.

**Comment by alexandreSalconiDenis** [comment]
Indeed the Local package override look good for that usage, we are starting to use it but it doesn't solve this issue. We develop embedded code so we never install the lib and some are Interfaces so this was our solution to get universal version for lib that would be harder to get otherwise. Also we want to use `VERSION` to specify the version, `GIT_TAG` is cool but only to fetch from git.

**Comment by TheLartians** [comment]
Tbh I'm still not sure I fully understand the use case yet. Determining the version used AFTER the project has been added won't allow warning users using the project to know if they actually requested a higher version than the one currently being used. 

Also note that you can currently specify `VERSION` and `GIT_TAG` independently, so you can still explicitly set the version in addition to a tag and get appropriate CPM.cmake behaviour.

**Comment by alexandreSalconiDenis** [comment]
Thats correct, I think the use case is too specific. The issue seems to be related on the way we work with cmake and cpm, it doesnt seems to be a frequent issue. I will then close the issue and the PR. Thanks for your help.
