### ISSUE TITLE
[Feature] prettify cpm_add_to_package_lock

### ISSUE THREAD

**Issue by alexandreSalconiDenis** [TheLartians/CPM.cmake#172]
I've added some prettify to the cpm_add_to_package_lock and cpm_add_comment_to_package_lock.
It's in PR #162

**Comment by alexandreSalconiDenis** [comment]
> Hey, thanks for the PR!
> I'm a bit hesitant as the package-lock was originally intended to be a small auto-generated file, and not rarely be human read or edited, but I do see that this can become more frequent. Also many projects have automatic code formatting enabled, so maybe instead of accepting the arguments in a string value, we should change the way `CPMDeclarePackage` works to accept the same arguments as `CPMAddPackage`. That way the auto code formatter would take care of any styling and be more consistent with the user's preferences.

I'm not sure how changing the way argument are pass will help. The prettify was set to help be human readable.
This is the result for unit:
```
# units
CPMDeclarePackage(units
    NAME units
    GIT_TAG v3.0.0.alpha-2
    GIT_REPOSITORY https://******/GitHub/units.git
    SOURCE_DIR ${CMAKE_SOURCE_DIR}/drivers/units
    OPTIONS
        "DISABLE_PREDEFINED_UNITS ON"
        "DISABLE_IOSTREAM ON"
)
```
In one project we have ~45 package declare inside package lock, if its not human readable it's hard to check when needed.
The string seems to be correct since if you get an option with space all the data is inside quote. readable 

And we dont use formatter for cmake file that's why we decided to pretty the auto-gen instead.
To avoid causing issue to other dev I can add an option to set the human readable auto-gen,`CPMHumanReadableLockFile` ?

**Comment by alexandreSalconiDenis** [comment]
@TheLartians if we add an option to enable the human readable version could it be correct ?

**Comment by TheLartians** [comment]
Hey, sorry for the late response I somehow missed your previous answer. After thinking about this a bit, I definitely see the value in a more human readable package lock. However, formatting the code is tricky and can introduce unforeseen bugs. E.g. we would need to specify **ALL** possible arguments that may get forwarded to FetchContent. For example, your current implementation does not support the `URL` argument and breaks if you try to add a package using its URL. Perhaps we could change your implementation to append all unparsed arguments as a list it may work, though we would still need to write some tests for it. 

My initial thought was to use a well tested linter tool, such as _cmake-format_, take care of the formatting after generating the package-lock, but unfortunately it doesn't seem to resolve semicolon separated lists.

**Comment by alexandreSalconiDenis** [comment]
I can check to add a way to put unparsed data at the end without formatting and in the future we could add them to the filter, i think for `URL` i could add it to the `oneValueArgs` list. I'm not familiar with the unit test used with cpm but I will look at it  to also make some test.

**Comment by TheLartians** [comment]
Yeah as long as all unparsed arguments still remain in the output in a valid way I think it could work. Maybe the algorithm could also be generalised without needing to explicitly list all possible arguments. E.g. if a parameter is in Snake Case (All Caps) it is most likely a named argument and should be at the beginning of a new line.

Regarding unit tests, you can check that existing tests still work by calling:

```bash
cmake -Stest -Bbuild/test
cmake --build build/test --target test-verbose
```

An additional unit test to check the prettified output would also be great.

**Comment by alexandreSalconiDenis** [comment]
I base my parsing on the function: [`CPMAddPackage`](https://github.com/TheLartians/CPM.cmake/blob/master/cmake/CPM.cmake#L238)  but I think in short term we could append the `CPM_ARGS_UNPARSED_ARGUMENTS` at the end of the list of each item. I think cmake accept that they will be on the same line. After that i can check to do the smart format on them like you told me with the Snake Case.

**Comment by alexandreSalconiDenis** [comment]
I've added some unit test but i'm not sure if the are strong enough: https://github.com/cimeq/CPM.cmake/blob/feature/prettifyPackageLock/test/unit/package-lock_prettify.cmake. tell me if it's enough or if we need to go further.

**Comment by TheLartians** [comment]
Let's move further discussion to to PR #162 itself!
