### ISSUE TITLE
DOWNLOAD_ONLY doing more than downloading

### ISSUE THREAD

**Issue by trxcllnt** [TheLartians/CPM.cmake#173]
Specifying `DOWNLOAD_ONLY` in `CPMAddPackage` or `CPMFindPackage` seems to be configuring the package.

Not sure if this is a CPM bug, or if I've misunderstood the behavior when `DOWNLOAD_ONLY` is present.

For example, this starts configuring the `libcu++` LLVM tests:

```cmake
cmake_minimum_required(VERSION 3.18 FATAL_ERROR)

project(LIBCUDACXX_CPM_TEST)

# Uses CPM v0.27.5
include(get_cpm.cmake)

CPMAddPackage(NAME  libcudacxx
    VERSION         1.4.0
    GIT_TAG         1.4.0
    GIT_REPOSITORY  https://github.com/NVIDIA/libcudacxx.git
    GIT_SHALLOW     TRUE
    DONWLOAD_ONLY   TRUE
)
```

**Comment by trxcllnt** [comment]
Nevermind, adding `EXCLUDE_FROM_ALL TRUE` to the CPM options achieves what I need.

I misunderstood https://github.com/TheLartians/CPM.cmake/issues/152 to indicate `EXCLUDE_FROM_ALL` wasn't supported.

**Comment by TheLartians** [comment]
I think this may be due to a typo in your script. Please try replacing `DONWLOAD_ONLY` with `DOWNLOAD_ONLY` and let me know if the issue persists.

**Comment by trxcllnt** [comment]
Oh my god. You're right, thank you. Sorry for wasting your time.

**Comment by TheLartians** [comment]
No worries, happens to the best of us 😄
