### ISSUE TITLE
CPM hangs when downloading files with invalid URL_HASH

### ISSUE THREAD

**Issue by AlxHnr** [TheLartians/CPM.cmake#174]
`URL_HASH` mismaches cause the download to be retried a few times in a row, with fixed sleep intervals in between. The lack of output during this time makes CMake look like its hanging. After about 2 minutes CMake terminates the configuration and prints all the download errors. These errors should ideally be printed while they happen so it doesn't look like its hanging.

Here is the example package with an invalid hash to reproduce my issue.

```cmake
CPMAddPackage(
  NAME SDL2
  VERSION 2.0.12
  URL https://www.libsdl.org/release/SDL2-2.0.12.zip
  URL_HASH SHA256=f
)
```

Here is the output at which CMake seems to hang:

```
-- CPM: adding package SDL2@2.0.12 (2.0.12)
```

**Comment by TheLartians** [comment]
By default, [FetchContent](https://cmake.org/cmake/help/git-stage/module/FetchContent.html) surpresses verbose output to not spam the console, so I'm afraid there isn't anything that CPM.cmake can do here. In the case of hanging downloads I'd recommend enabling verbose downloads by providing the additional argument `-DFETCHCONTENT_QUIET=Off` to CMake, e.g.

```bash
cmake -S. -Bbuild -DFETCHCONTENT_QUIET=Off
```

Which should show you what's going on under the hood.

**Comment by AlxHnr** [comment]
I close this issue, since this is CMakes default behavior.
