### ISSUE TITLE
Multiple versions of CPM?

### ISSUE THREAD

**Issue by hdf89shfdfs** [TheLartians/CPM.cmake#175]
I want to use CPM at my company but I'm concerned about the following types of scenarios. That could easily occur if every project is individually downloading CPM.

Project A uses CPM 0.27.5
Project B uses CPM 1.01.0
Project C uses CPM 0.10.0

What happens if project A uses project B?

What happens if project B uses project A?

What happens if project B uses project C?

What happens if project C uses project B?

**Comment by TheLartians** [comment]
Hey, CPM always keeps the first version used, but emits a warning if a (semantic) newer version is requested. You can see the logic [here](https://github.com/TheLartians/CPM.cmake/blob/cf3f62b6f26e6a5bef477f12b7f51eb1d5e0cbe7/cmake/CPM.cmake#L35).  In your examples:

 > What happens if project A uses project B?

The Project uses CPM 0.27.5, but a warning is emitted that B requires the more recent 1.01.0

> What happens if project B uses project A?

The Project uses CPM 1.01.

> What happens if project B uses project C?

The Project uses CPM 1.01.0

> What happens if project C uses project B?

The Project uses CPM 0.10.0, but a warning is emitted that B requires the more recent 1.01.0

**Comment by hdf89shfdfs** [comment]
Gotcha that makes sense. 

Is something like this worth adding to the wiki/readme? 

Or is this just expected cmake behavior? Because I believe vanilla FetchContent uses the same logic you described.

**Comment by TheLartians** [comment]
It's already kind-of mentioned in the: [readme](https://github.com/TheLartians/CPM.cmake#updating-cpm) `Dependencies using CPM will automatically use the updated script of the outermost project.`, but if you feel this isn't clear enough feel free to add it to the wiki. :)

**Comment by hdf89shfdfs** [comment]
Yeah as soon as I said it, I started looking at the readme... and sure enough it was there. Sorry that's a bad habit of mine.

I think it's clear in the README.md, just that the readme is huge and my eyes tend to glaze when the readme is too large. It may be worth moving more stuff into the wiki. But that's just my opinion.

**Comment by TheLartians** [comment]
I think most of us have that habit. 😄 

I agree that the README has gotten rather huge and we can probably outsource move some to the wiki. Thanks for noting it, once I have some spare time I'll see if I can slim things down.
