### ISSUE TITLE
CPM: IODash not found via find_package(IODash )

### ISSUE THREAD

**Issue by bhepple** [TheLartians/CPM.cmake#178]
I'm tryiing to build [ydotool](https://github.com/ReimuNotMoe/ydotool) which is a package using CPM.make. This is for fedora and they do not allow builds using in-build downloads - I have to provide a versioned tarball including all the dependencies.

ydotool has several dependencies including [IODash](https://github.com/YukiWorkshop/IODash)

I'm trying to use -DCPM_IODash_SOURCE=/path/to/source but I always get the error:

```
  CPM: IODash not found via find_package(IODash )
Call Stack (most recent call first):
  CPM.cmake-0.27.5/cmake/CPM.cmake:252 (CPMAddPackage)
  CMakeLists.txt:16 (CPMAddPackage)

-- CPM: adding package IODash@ (/home/bhepple/rpmbuild/BUILD/ydotool-0.2.0/x86_64-redhat-linux-gnu/IODash-0.1.0)
```

I've tried dropping a plain source tarball as well as a git repo at that location but neither work.

The full cmake invocation is: 

```
cmake -S . -B x86_64-redhat-linux-gnu -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG \
-DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG \
-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr \
/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc \
-DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_SUFFIX=64 -DBUILD_SHARED_LIBS:BOOL=ON \
-DCPM_USE_LOCAL_PACKAGES:BOOL=TRUE -DCPM_LOCAL_PACKAGES_ONLY:BOOL=TRUE \
-DCPM_IODash_SOURCE=/home/bhepple/rpmbuild/BUILD/ydotool-0.2.0/x86_64-redhat-linux-gnu/IODash-0.1.0 \
-DCPM_libevdevPlus_SOURCE=/home/bhepple/rpmbuild/BUILD/ydotool-0.2.0/libevdevPlus-0.2.1 \
-DCPM_libuInputPlus_SOURCE=/home/bhepple/rpmbuild/BUILD/ydotool-0.2.0/libuInputPlus-0.2.1 \
-DCPM_cxxopts_SOURCE=/home/bhepple/rpmbuild/BUILD/ydotool-0.2.0/cxxopts-2d8e17c4f88efce80e274cb03eeb902e055a91d3
```

the directory /home/bhepple/rpmbuild/BUILD/ydotool-0.2.0/x86_64-redhat-linux-gnu/IODash-0.1.0 definitely contains the source tarball from [IODash](https://github.com/YukiWorkshop/IODash)...

```
$ ls /home/bhepple/rpmbuild/BUILD/ydotool-0.2.0/x86_64-redhat-linux-gnu/IODash-0.1.0 
Benchmarks  CMakeLists.txt  cpp_modules  IODash  IODash.cpp  IODash.hpp  LICENSE  README.md  test.cpp
```

I've also tried putting the full git repo there but I get the same error.

Any ideas for me?

PS the top level CMakeLists.txt file for ydotool has been patched to:

```
cmake_minimum_required(VERSION 3.14)
project(ydotool)

set(CMAKE_CXX_STANDARD 17)

set(CPM_DOWNLOAD_VERSION 0.27.5)
set(CPM_DOWNLOAD_LOCATION "CPM.cmake-${CPM_DOWNLOAD_VERSION}/cmake/CPM.cmake")

if(NOT (EXISTS ${CPM_DOWNLOAD_LOCATION}))
    message(STATUS "Downloading CPM.cmake")
    file(DOWNLOAD https://github.com/TheLartians/CPM.cmake/releases/download/v${CPM_DOWNLOAD_VERSION}/CPM.cmake ${CPM_DOWNLOAD_LOCATION})
endif()

include(${CPM_DOWNLOAD_LOCATION})

CPMAddPackage(
        NAME IODash
        GITHUB_REPOSITORY YukiWorkshop/IODash
        VERSION 0.1.0
)
...
```

**Comment by TheLartians** [comment]
It looks like you've enabled the flags [`-DCPM_USE_LOCAL_PACKAGES=YES` and `-DCPM_LOCAL_PACKAGES_ONLY=YES`](https://github.com/TheLartians/CPM.cmake#cpm_use_local_packages). This combination tells CPM.cmake to look for packages exclusively using the standard `find_package` command and error in case it isn't found. Therefore the flag `CPM_IODash_SOURCE` is not used, as it isn't consumed by `find_package`.
I would suggest either ensuring that all required dependencies are installed by the system package manager in a way that `find_package` can find them or to remove the `-DCPM_LOCAL_PACKAGES_ONLY=YES` flag and provide the source and location explicitly as you have done.

**Comment by bhepple** [comment]
Awesome! Remoing those flags did the trick:

```
-- CPM: adding package IODash@ (/home/bhepple/rpmbuild/BUILD/ydotool-0.2.0/x86_64-redhat-linux-gnu/IODash-0.1.0)
-- CPM: adding package libevdevPlus@ (/home/bhepple/rpmbuild/BUILD/ydotool-0.2.0/x86_64-redhat-linux-gnu/libevdevPlus-0.2.1)
-- CPM: adding package libuInputPlus@ (/home/bhepple/rpmbuild/BUILD/ydotool-0.2.0/x86_64-redhat-linux-gnu/libuInputPlus-0.2.1)
-- CPM: adding package cxxopts@ (/home/bhepple/rpmbuild/BUILD/ydotool-0.2.0/x86_64-redhat-linux-gnu/cxxopts-2d8e17c4f88efce80e274cb03eeb902e055a91d3)
-- cxxopts version 3.0.0
```

Now I can stumble on to the next one ...

Big thanks for the fast and helpful reply - I've been stuck for a couple of days now!!

**Comment by bhepple** [comment]
Can close this now.
