### ISSUE TITLE
Enable discussions for the repo

### ISSUE THREAD

**Issue by iboB** [TheLartians/CPM.cmake#183]
I think enabling [GitHub discussions](https://docs.github.com/en/discussions/quickstart) for this repo is in order. It's a good place to have info, answered questions and other non-strictly-issue related conversations. Issues can work to some extent for the same purpose, but issues should be opened and closed, while discussions remain

**Comment by TheLartians** [comment]
Interesting, haven't heard of GitHub discussions before, but it does look really nice! I just opened up the discussions for this repo. We have already opened a Gitter room before (#153), however there hasn't been much activity until now and the centralised solution does look neat.
