### ISSUE TITLE
CPM Option Parse Error if Option Doesn't Have Key/Value Syntax

### ISSUE THREAD

**Issue by DeveloperPaul123** [TheLartians/CPM.cmake#95]
The `cpm_parse_option` function fails if the list of options don't follow the key/value format. I discovered this with the following code:

````cmake
CPMAddPackage(
    NAME googletest
    GITHUB_REPOSITORY google/googletest
    GIT_TAG release-1.8.1
    VERSION 1.8.1
    OPTIONS
       "INSTALL_GTEST OFF"
       "gtest_force_shared_crt ON"
       "GTEST_HAS_STD_TUPLE"
)
````

Error message: `string begin index: 20 is out of range 0 - 19` on line 196 of `CPM.cmake`.
The issue goes away if you do the following instead:

````cmake
CPMAddPackage(
    NAME googletest
    GITHUB_REPOSITORY google/googletest
    GIT_TAG release-1.8.1
    VERSION 1.8.1
    OPTIONS
       "INSTALL_GTEST OFF"
       "gtest_force_shared_crt ON"
       "GTEST_HAS_STD_TUPLE ON"
)
````

**Comment by TheLartians** [comment]
I'm unsure what the expected outcome should be if we supply only the key and no value.
Should we default to `set(${key},1)` or rather print a warning / error that the value is missing?

**Comment by DeveloperPaul123** [comment]
Is a value always required? I think it's sensible that if one if defining an option like that, their intent is to turn it "ON".

**Comment by TheLartians** [comment]
Fair enough, I'll prepare the update later today.

**Comment by DeveloperPaul123** [comment]
Awesome, thanks!
